### ISSUE TITLE
Refactor Repository

### ISSUE THREAD

**Issue by mathildemarcussen** [ITU-BDSA2024-GROUP21/Chirp#149]
- [x] Cheep repository (CheepDTO)
- [x] Author repository (AuthorDTO)
- [x] Follow repository (AuthorFollowDTO (Create one)

**Comment by jjyutm4532** [comment]
Hello, I tried to solve the issue.

This is what I did:

We'll create new repository classes for Cheep, Author, and Follow, along with their respective DTOs. We'll also update the existing files to accommodate these changes.

You can review changes in this commit: https://github.com/jjyutm4532/ITU-BDSA2024-GROUP21-Chirp-149/commit/051e2c2a390d4904c9920f7c59773a10d88a0d51.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
